nome=input('Qual o seu nome? \n')
print(f'Olá, {nome:=^10}. Seja bem vindo.')
n1=int(input('\nInsira um valor: '))
n2=int(input('Insira outro valor: '))
s=(n1+n2)
m=(n1*n2)
div=(n1/n2)
sub=(n1-n2)
pot=pow(n1,n2)
print(f'\nA soma vale {s}. \nA subtração vale {sub}. \nA multiplicação vale {m}. \nA divisão vale {div:.2f}.',end='> ')
print(f'A potência vale {pot}.')
n3=int(input('\nColoque um valor: '))
print(f'Seu antecessor é {n3-1} e seu sucessor é {n3+1}.')
print(f'\nDo seu primeiro valor \nSeu dobro é {n3*2}, seu triplo é {n3*2} e sua raiz quadrada é {n3**1/2:.2f}.')
print('\nFaça uma média')
n4=int(input('Coloque um valor: '))
n5=int(input('Coloque um outro: '))
print(f'Sua média é {(n4+n5)/2}.\n')
n6=int(input('Coloque um valor: '))
print(f'Em centímetros {n6:.2f}. Em milímetro {n6:.4f}.')
print('\nFaça a sua tabuada')
n7=int(input('Insira um número: '))
print('='*20)
print(f'Tabuada de {n7}')
print(f'{n7}x1={n7*1}')
print(f'{n7}x2={n7*2}')
print(f'{n7}x3={n7*3}')
print(f'{n7}x4={n7*4}')
print(f'{n7}x5={n7*5}')
print(f'{n7}x6={n7*6}')
print(f'{n7}x7={n7*7}')
print(f'{n7}x8={n7*8}')
print(f'{n7}x9={n7*9}')
print(f'{n7}x10={n7*10}')
print('='*20)
print('\nConversão de real para dolar')
real=float(input('R$ '))
dolar=real*3.27
print(f'Você tem ${dolar:.2f}.')
print(f'\nDescubra a área da parede para pintar.')
largura=float(input('Insira a largura: '))
altura=float(input('Insira a altura: '))
area=largura*altura
tinta=area/2
print(f'Sua área é de {area}. {tinta} latas de tinta para pintar completamente.')
print(f'\nColoque o valor do produto')
produto=float(input('R$'))
desconto=produto*(5/100)
print(f'Parabéns, você ganhou 5% de desconto. Você precisará pagar apenas R${produto-desconto:.2f}.')
print(f'\nInsira o seu salário')
salario=float(input('R$'))
aumento=salario*(15/100)
print(f'Você ganhou um aumento de 15%. Agora você recebe R${salario+aumento:.2f}.')