a=input('Digite algo: ')
print('o valor primitivo desse valor é ',type(a))
print('Só tem espaços?', a.isspace())
print('Só tem letra?', a.isalpha())
print('Só tem número?',a.isnumeric())
print('Está em alphanumérico?',a.isalnum())
print('Está em maiúsculo?',a.isupper())
print('Está em minúsculo?',a.islower())
print('Está capitalizada?',a.istitle())